### ISSUE TITLE
SharePoint Online use Prime API restore OneNote file failed

### ISSUE THREAD

**Issue by LeoJiang1988** [MicrosoftDocs/OfficeDocs-SharePoint#1601]
Hi Team,

We use SharePoint Online Prime API to restore OneNote files failed.
The Queue Message like:
 Message:Error=Value=OneNoteUpgradeNotSupported, Tag=0x0121d3da, Message=Upgrade blocked: OneNote file is not located within a Notebook folder. The file will not be upgraded. CallStack --    at Cobalt.RequestBatch.ThrowIfAnyError()
   at Cobalt.PackagingUtils.PutStream(ByteData data, CobaltEndpoint endpoint)
   at Microsoft.SharePoint.Utilities.SPBITSSession.<>c__DisplayClass1d.<SetStream>b__17()
   at Cobalt.ExceptionRetry.RetryTransientExceptions(Action action, Boolean allowRetry, Action actionBeforeRetry)
   at Microsoft.SharePoint.Utilities.SPBITSSession.SetStream(SPFile file, Nullable`1 levelOverride, StreamPath streamPath, Stream content, SPFileSaveBinaryParameters saveBinaryParams, Boolean retryTransientFailures, Boolean isDiffGram, StreamAccessHints streamAccessHints, Byte[] finalDataHash)
   at Microsoft.SharePoint.Deployment.FileSerializer.CreateOrUpdateFileWithGuid(Stream spstm, SPLoggerObject loggerObject, SPWeb web, Guid fileId, SPResourcePath filePath, Int32 authorId, String authorLoginName, Int32 editorId, String editorLoginName, String checkinComment, DateTime timeCreated, DateTime timeLastModified, MetaInfoHandler metaInfo, Int32 length, Int32 iVersion, Boolean isFirstVersion, SPImportSettings settings, Int32 listItemId, String listInternalName, Boolean hasNoExecuteFlag, ImportObjectManager objectManager)
        CorrelationId:eb04219f-f0d8-a000-66e5-2283b8500e16

**Comment by scanum** [comment]
@LeoJiang1988 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
