### ISSUE TITLE
White screen after authenticating to on-prem

### ISSUE THREAD

**Issue by HennepinCrawler** [MicrosoftDocs/OfficeDocs-SharePoint#2477]
SharePoint 2013 May 2020 CU on Windows 2008 R2 SP1 (updated .Net framework to 4.6.2) --

After authenticating to M365 and then selecting the site I am prompted to authenticate to the on-prem SharePoint server.  I put in the credentials, appears to accept them and then goes to a 'white screen' where it hangs.   Any ideas?
![image](https://user-images.githubusercontent.com/2495201/101416849-451f2280-38b0-11eb-81b8-679a4ec1bf03.png)

**Comment by HennepinCrawler** [comment]
Please close this out, I found the logs and the customer had Fab40 installed at one point.  May be nice to document this for another person I guess.

ERROR|GLB|24|Cannot get document library for site <https://site> for user xxx\xxxx Microsoft.SharePoint.MigrationTool.MigrationLib.SharePoint.MigSPNotFoundException: Web Issue when doing SP Query ---> Microsoft.SharePoint.Client.ServerException: Feature '75a0fea7-625d-4b31-be9e-24cee53d0d72' for list template **'1009'** is not installed in this farm.  The operation could not be completed.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.MigrationTool.MigrationLib.SharePoint.MigSPClientContext.WrapExceptions(Action logicToRetry)
   --- End of inner exception stack trace ---
