### ISSUE TITLE
Unable to download and install SPMT

### ISSUE THREAD

**Issue by kevinleary** [MicrosoftDocs/OfficeDocs-SharePoint#572]
I was able to do a migration from a server on our network a couple of weeks ago. I now get an error after it is prompted to update and I except, or when installing the app again. This was working on the same machines where its not only a couple of weeks ago. 

Here is the detailed error: 
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3062.0 built by: NET472REL1
	clr.dll 			: 4.7.3062.0 built by: NET472REL1
	dfdll.dll 			: 4.7.3062.0 built by: NET472REL1
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/Users/kleary/Downloads/build.application
	Deployment Provider url		: http://spmtreleasescus.blob.core.windows.net/build/build.application
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
	Application url			: http://spmtreleasescus.blob.core.windows.net/build/migrationtoolinstall/microsoft.sharepoint.migrationtool.advancedapp.exe.manifest
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

IDENTITIES
	Deployment Identity		: SharePoint Migration Tool, Version=2.1.103.8510, Culture=neutral, PublicKeyToken=ee2520a84441d7e2, processorArchitecture=msil
	Application Identity		: Microsoft.SharePoint.MigrationTool.AdvancedApp, Version=2.1.103.8510, Culture=neutral, PublicKeyToken=ee2520a84441d7e2, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\kleary\Downloads\build.application resulted in exception. Following failure messages were detected:
		+ File, libcef.dll, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [1/14/2019 2:55:07 PM] : Activation of C:\Users\kleary\Downloads\build.application has started.
	* [1/14/2019 2:55:07 PM] : Processing of deployment manifest has successfully completed.
	* [1/14/2019 2:55:07 PM] : Installation of the application has started.
	* [1/14/2019 2:55:07 PM] : Processing of application manifest has successfully completed.
	* [1/14/2019 2:55:09 PM] : Found compatible runtime version 4.0.30319.
	* [1/14/2019 2:55:09 PM] : Detecting dependent assembly System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [1/14/2019 2:55:09 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [1/14/2019 2:55:29 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, libcef.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tomcrinnegan** [comment]
Similar issue here - but refers to a different .dll

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\Users\170287\Downloads\build-firstrelease.application resulted in exception. Following failure messages were detected:
		+ File, oncloudify_x86.dll, has a different computed hash than specified in manifest.

ERROR DETAILS
	Following errors were detected during this operation.
	* [23/01/2019 2:48:57 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, oncloudify_x86.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by kevinleary** [comment]
Any update on this? Our migration would be significantly improved rather than having to work on migrating using powershell 3

**Comment by JoanneHendrickson** [comment]
Hi Kevin:  If you haven't already, I would open a support call for this issue.  It is difficult without digging in to see if your installation issue is unique to your environment.

**Comment by kevinleary** [comment]
Hi Joanne,

I already went on a support call about 3 weeks ago and the issue was not
resolved. It was suggested that I use Powershell instead. The error I get
is after installation completes it says "application validation failed"

Thanks,

Kevin Leary

**Comment by scanum** [comment]
@kevinleary  - thank you for submitting feedback.

As @JoanneHendrickson Joanne mentioned, I think the best way forward is if you follow up on the service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocs close
