### ISSUE TITLE
Application validation did not succeed

### ISSUE THREAD

**Issue by Abenold** [MicrosoftDocs/OfficeDocs-SharePoint#663]
Hi since the last Versions we are not able to Install any Versions of  the SPMT  maybe you could help?
We get the following error in the log:

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3221.0 built by: NET472REL1LAST_C
	clr.dll 			: 4.7.3260.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3221.0 built by: NET472REL1LAST_C
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: https://spmtreleasescus.blob.core.windows.net/betabuild/betabuild.application
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
	Deployment Provider url		: http://spmtreleasescus.blob.core.windows.net/betabuild/betabuild.application
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
	Application url			: http://spmtreleasescus.blob.core.windows.net/betabuild/migrationtoolinstall/microsoft.sharepoint.migrationtool.advancedapp.exe.manifest
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

IDENTITIES
	Deployment Identity		: SharePoint Migration Tool, Version=3.0.104.8529, Culture=neutral, PublicKeyToken=4fcf69302149948a, processorArchitecture=msil
	Application Identity		: Microsoft.SharePoint.MigrationTool.AdvancedApp, Version=3.0.104.8529, Culture=neutral, PublicKeyToken=ee2520a84441d7e2, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://spmtreleasescus.blob.core.windows.net/betabuild/betabuild.application resulted in exception. Following failure messages were detected:
		+ File, libcef.dll, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [12.02.2019 12:48:40] : Activation of https://spmtreleasescus.blob.core.windows.net/betabuild/betabuild.application has started.
	* [12.02.2019 12:48:41] : Processing of deployment manifest has successfully completed.
	* [12.02.2019 12:48:41] : Installation of the application has started.
	* [12.02.2019 12:48:42] : Processing of application manifest has successfully completed.
	* [12.02.2019 12:48:48] : Found compatible runtime version 4.0.30319.
	* [12.02.2019 12:48:48] : Detecting dependent assembly System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [12.02.2019 12:48:48] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12.02.2019 12:52:02] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, libcef.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kevinleary** [comment]
I am having the same app validation issue on both versions and it hasn't been fixed for about a month.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Abenold** [comment]
any updates, still having that issue.

**Comment by VLG17** [comment]
@Abenold from the error i can see that you are trying to install the beta release of the SPMT, right? Could you also try with the current version - https://spmtreleasescus.blob.core.windows.net/install/default.htm?

More info on the 2 SPMT releases - https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

If you get the same error, i would recommend to open a case with Sharepoint Online Support (from Office 365 Portal -> Need help?)

**Comment by scanum** [comment]
@Abenold  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
